### PR TITLE
feat: zh_cn doc

### PR DESCRIPTION
**Pull request by hehehai**

### CODE REVIEW

**Comment by hehehai** [comment]
Proofreading

**Comment by Siumauricio** [comment]
Thank you so much!

Can you resolve the conflicts please?

**Comment by hehehai** [comment]
> Thank you so much!
>
> Can you resolve the conflicts please?

Yes, I will formally submit it after proofreading is completed later.

**Review by Siumauricio — APPROVED** [review]
Amazing, Thank you!

**Pull request merged**
