### PR TITLE
feat: zh_cn doc & add descriptions about --advertise-addr parameter

### PR DESCRIPTION
**Pull request by binaryYuki**

### CODE REVIEW

**Comment by binaryYuki** [comment]
PR Summary:
- Updated `uninstall.cn.mdx` for localization.
- Added custom address documentation (`addr docs`).
- Created `manual-installation.cn.mdx`.
- Translated `manual-installation` into Chinese.
- Translated feature documentation into Chinese.
- Translated architecture documentation into Chinese.
- Fixed error in reference URL in introduction.cn.mdx
- enhanced descriptions for `--advertise-addr` parameter.

**Comment by binaryYuki** [comment]
Hi @Siumauricio,

Happy to let you know that this PR is now ready for review.

PR Summary:

- Updated uninstall.cn.mdx for localization.
- Translated manual-installation doc into Chinese.
- Translated feature documentation into Chinese.
- Translated architecture documentation into Chinese.
- Fixed error in reference URL in introduction.cn.mdx
- add descriptions for --advertise-addr parameter.

**Comment by Siumauricio** [comment]
Thanks @binaryYuki, can you check this? 
image

in the docs websites is working fine 
image

**Comment by binaryYuki** [comment]
Hi @Siumauricio ,

It works functionally in my device.

I think it should related #13 .

I'll try to fix it and let you know when this pr's ready.

Sorry for the delay.

**Comment by binaryYuki** [comment]
Hi @Siumauricio ,

Happy to let you know everything's done!

I also fix an error while refactoring in #14 .

**Comment by binaryYuki** [comment]
All set!

**Comment by Siumauricio** [comment]
Thank you ❤️ @binaryYuki

**Review by Siumauricio — APPROVED** [review]

**Pull request merged**
